const GET_GLOBAL_PARAMETERS = 'GET_GLOBAL_PARAMETERS';
const SUCCESS_GET_GLOBAL_PARAMETERS = 'SUCCESS_GET_GLOBAL_PARAMETERS';

const GET_LABELS = 'GET_LABELS';
const SUCCESS_GET_LABELS = 'SUCCESS_GET_LABELS';

const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
const SUCCESS_GENERATE_PASSWORD = 'SUCCESS_GENERATE_PASSWORD';

const LOGIN_WITH_CODE = 'LOGIN_WITH_CODE';
const SUCCESS_LOGIN_WITH_CODE = 'SUCCESS_LOGIN_WITH_CODE';
const FAILED_LOGIN_WITH_CODE = 'FAILED_LOGIN_WITH_CODE';
const GET_CURRENT_USER = 'GET_CURRENT_USER';
const SUCCESS_GET_CURRENT_USER = 'SUCCESS_GET_CURRENT_USER';
const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
const SUCCESS_UPDATE_CURRENT_USER = 'SUCCESS_UPDATE_CURRENT_USER';

export {
  GET_GLOBAL_PARAMETERS,
  SUCCESS_GET_GLOBAL_PARAMETERS,
  GET_LABELS,
  SUCCESS_GET_LABELS,
  GENERATE_PASSWORD,
  SUCCESS_GENERATE_PASSWORD,
  LOGIN_WITH_CODE,
  SUCCESS_LOGIN_WITH_CODE,
  FAILED_LOGIN_WITH_CODE,
  GET_CURRENT_USER,
  SUCCESS_GET_CURRENT_USER,
  UPDATE_CURRENT_USER,
  SUCCESS_UPDATE_CURRENT_USER,
}