const GET_GLOBAL_PARAMETERS = 'GET_GLOBAL_PARAMETERS';
const SUCCESS_GET_GLOBAL_PARAMETERS = 'SUCCESS_GET_GLOBAL_PARAMETERS';

const GET_LABELS = 'GET_LABELS';
const SUCCESS_GET_LABELS = 'SUCCESS_GET_LABELS';

const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
const SUCCESS_GENERATE_PASSWORD = 'SUCCESS_GENERATE_PASSWORD';

const LOGIN_WITH_CODE = 'LOGIN_WITH_CODE';
const SUCCESS_LOGIN_WITH_CODE = 'SUCCESS_LOGIN_WITH_CODE';
const FAILED_LOGIN_WITH_CODE = 'FAILED_LOGIN_WITH_CODE';

export {
  GET_GLOBAL_PARAMETERS,
  SUCCESS_GET_GLOBAL_PARAMETERS,
  GET_LABELS,
  SUCCESS_GET_LABELS,
  GENERATE_PASSWORD,
  SUCCESS_GENERATE_PASSWORD,
  LOGIN_WITH_CODE,
  SUCCESS_LOGIN_WITH_CODE,
  FAILED_LOGIN_WITH_CODE,
}