const GET_GLOBAL_PARAMETERS = 'GET_GLOBAL_PARAMETERS';
const SUCCESS_GET_GLOBAL_PARAMETERS = 'SUCCESS_GET_GLOBAL_PARAMETERS';

const GET_LABELS = 'GET_LABELS';
const SUCCESS_GET_LABELS = 'SUCCESS_GET_LABELS';

const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
const SUCCESS_GENERATE_PASSWORD = 'SUCCESS_GENERATE_PASSWORD';

export {
  GET_GLOBAL_PARAMETERS,
  SUCCESS_GET_GLOBAL_PARAMETERS,
  GET_LABELS,
  SUCCESS_GET_LABELS,
  GENERATE_PASSWORD,
  SUCCESS_GENERATE_PASSWORD,
}